<?php

DEFINE('PROJECT_NAME', 'Cultura do Campo');
#TEMPO DE VIDA DO COOKIE DO LOGIN
DEFINE('LOGIN_COOKIE_LIFETIME', 86400);
#
DEFINE('LOGIN_MAX_FAILED_ATTEMPTS', 10);
DEFINE('LOGIN_NUMBER_ATTEMPS_DELAY', 5);
DEFINE('LOGIN_SLEEP_BASE_DELAY', 2);
DEFINE('LOGIN_FAILED_ATTEMPTS_RANGE', 15); // em minutos 
DEFINE('LOGIN_RECAPTCHA', TRUE);
DEFINE('LOGIN_CAPTCHA_SECRET', '6Le8m4QUAAAAAIJ1IykZy0aEMkaVUASnyKKwIzEm');

#
DEFINE('TIMEZONE', 'America/Sao_Paulo');
#
DEFINE('MAIL_USERNAME', 'app.culturadocampo@gmail.com');
DEFINE('MAIL_PASSWORD', 'InfoDmz626');
DEFINE('MAIL_SMPT', 'smtp.gmail.com');
DEFINE('MAIL_PORT', 465);
DEFINE('MAIL_PROTOCOL', 'ssl');
#
DEFINE('MASTER_PASSWD', '123');





